### ISSUE TITLE
elementCount bug

### ISSUE THREAD

**Issue by songxiaoliang** [mjinkens1/react-native-circle-list#1]
When I set the elementCount to 6, I can't see the data point, I look forward to your reply.

` <CircleList
                data={mockData}
                elementCount={6}
                flatness={0.01}
                keyExtractor={this.keyExtractor}
                radius={RADIUS}
                innerRef={(component) => {
                    this.circleList = component;
                }}
                renderItem={this.renderItem}
                // onScrollEnd={(index) => this.circleList.scrollToIndex(8)}
            />`

**Comment by mjinkens1** [comment]
Due to the way the circular list is implemented, too low of an element count will cause improper rendering of the list as you have experienced.  For now the package will only support lists of 12 elements or more.  I've published a change to where any element count below 12 will have no effect, and the list will have at least 12 elements.  

If this does not fit your use case, one workaround may be to simply repeat your list of data until it is at least 12 elements long.  I will look into supporting lower element counts as time allows, but for now I'm marking this closed.  Thanks!
